# Generated by Django 5.0.6 on 2024-07-07 03:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserType', models.CharField(choices=[('Recruiter', 'Recruiter'), ('JobSeeker', 'JobSeeker')], max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(choices=[('Recruiter', 'Recruiter'), ('JobSeeker', 'JobSeeker')], max_length=50, null=True)),
                ('ProfilePicture', models.ImageField(null=True, upload_to='media/profile')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fathername', models.CharField(max_length=50, null=True)),
                ('Mothername', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('MaritalStatus', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried')], max_length=50, null=True)),
                ('portaluser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basicinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.CharField(max_length=50, null=True)),
                ('EmergencyContact', models.CharField(max_length=50, null=True)),
                ('PresentAddress', models.CharField(max_length=100, null=True)),
                ('PermanentAddress', models.CharField(max_length=100, null=True)),
                ('portaluser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=50, null=True)),
                ('PassingYear', models.CharField(max_length=50, null=True)),
                ('Grade', models.CharField(max_length=50, null=True)),
                ('Department', models.CharField(max_length=50, null=True)),
                ('portaluser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educationalinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('company_description', models.CharField(max_length=100, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='media/jobmodel')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_location', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('deadline', models.DateField(null=True)),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('profileimage', models.ImageField(null=True, upload_to='media/seeker_img')),
                ('resume', models.FileField(null=True, upload_to='media/seeker_resume')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicantuser', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobPortalApp.jobmodel')),
            ],
        ),
    ]
